### ISSUE TITLE
Improved pumpkin vanity item

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#129]
I discovered [this model](https://opengameart.org/content/jack-o-lantern) on OGA, decided to turn it into a vanity item, which is a huge improvement over the existing one. The current "pumpkin" vanity item is very low poly, and the texture also low res. This model has eye/mouth cut outs which is another improvement in appearance, especially as to being able to see the players eyes glowing inside.

I placed the files in the community repo to test/play with;
https://github.com/redeclipse/community/tree/master/unixfreak/vanities/pumpkin2 

One thing that needs looking at, are suggestions on the iqm.cfg as for the colour palettes. 

Here's a screenshot;

![preview](https://raw.githubusercontent.com/redeclipse/community/master/unixfreak/vanities/pumpkin2/preview.jpg)

**Comment by Dziq84** [comment]
very nice indeed,  I planned to replace old pumpkin and even started to make one
![blender_2019-09-30_20-26-25](https://user-images.githubusercontent.com/13541407/65905396-c3d12380-e3c0-11e9-8536-f80b3b2d752b.jpg)
Your one looks almost exactly how I wanted to do ^.^ .
My suggestion is to leave original pumpkin color and use only slight masking color :) - I mean less impact of player color

**Comment by Jigoku** [comment]
@Dziq, you can take a look at it and fix it up if you want. Most of the config was guesswork (still lacking docs on iqm related usage). I'm not sure how to generate a mask; but you can grab the blend file for this on the OpenGameArt link above, use the lowres/600 verts version.

**Comment by Dziq84** [comment]
I will make a mask for it and do little tweaks, I spotted a few issues in game that need to be resolved. Also not sure if 1200 poly for vanity is ok, the entire player model has around 3000,  @qreeves  - can you confirm if 1200 is ok?

**Comment by qreeves** [comment]
It's pushing it probably, but you could always LOD it if the detail is only necessary at close range.

**Comment by Dziq84** [comment]
so here is a result - 772 tris without any loss of quality, mostly by removing inside faces and merging close verts.  The mesh is colored now with player color, but very slightly - giving a bit different result based on chosen color.
Also, I repositioned it so it works better with other vanities, notice how bug eyes are visible giving a bit more 'scary' appearance (notice also that player color is delivered more to inside of mesh.
Also now it does not overlap with rat, I not checked with panda but probably no way to have both not overlapping due to the size of pumpkin ( I tried to make it as smallest as possible anyway).

![20191001162545](https://user-images.githubusercontent.com/13541407/65972439-20d4e400-e46a-11e9-8f13-a77d467c7946.jpg)
![20191001162626](https://user-images.githubusercontent.com/13541407/65972480-2c280f80-e46a-11e9-88d0-acdbd0dc03f8.jpg)

Textures are reworked too - less RGB information so files are smaller in size too
![explorer_2019-10-01_16-29-50](https://user-images.githubusercontent.com/13541407/65972501-3518e100-e46a-11e9-8bd5-3639ba0b6f43.jpg)

I consider this as ready to be merged. Jigoku, if you wish to do a PR by yourself I can send you files. If not I can do it

**Comment by Jigoku** [comment]
@Dziq84 Go ahead with the PR. Looks much better.

**Comment by Dziq84** [comment]
done :)

**Comment by Jigoku** [comment]
Noticed your PR was merged so i'll close this
