### ISSUE TITLE
Mine colors should be team specific when thrown.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#143]
Something that has always been in talks whitin the community regarding the use of mines, is that when thrown/you see them on the ground, one can't really know if they are from your team, or the enemy, causing unwanted teamkills.

So, by coloring them with the same color of your team when you pick up/throw will probably solve this issue.

As for anything other than a team gamemode, they can remain green as it is.

**Comment by molexted** [comment]
Is it useful information though? The mine will still kill you regardless of its colour.

**Comment by JeffBobbo** [comment]
> Is it useful information though? The mine will still kill you regardless of its colour.

This was my thought, the only other benefit is you know not to shoot your own mines. This would be more useful if mines couldn't be tripped by yourself/team mates, in which case you can identify that it's safe to proceed.

**Comment by molexted** [comment]
Note that mines cannot be tripped using projectiles as of https://github.com/redeclipse/base/commit/29ee4b51a6f35714bae520a1ff3739026bdc7093 since they're now fairly rare spawns (only a couple per medium map with 60s respawn time) and to allow metas other than just plastering them around blind corners (you can use them to openly control a corridor now without them being trivially destroyed).

There is no distinction between your mine and other people's mines anyways mechanics wise, so I'm still not sure it matters that the mine owner is explicitly labeled. Axing mine tk ability is plausible, but it'd likely make things like affinity defense too easy (the part collision change already makes this very easy).
