### ISSUE TITLE
Make blood come out from the neck after you headshot a enemy.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#145]
Something i've been thinking..
When you headshot a enemy with a rifle, and rips their head off, there's barely any blood that comes out.
What if the blood particles just kept coming off from the neck bone for that, until the player/enemy respawns?

**Comment by Rafirzm** [comment]
I think it will be fine for it to be solved meanwhile this issue with particle effects doesn't need to be discussed since it doesn't concern the game in general but the particle effect integration into this game. Still, some game greatly build with Tesseract benefits a tremendeous gestion of particules as well.

**Comment by q009** [comment]
Particle overhaul already on my TODO list.
