### ISSUE TITLE
Lost Castle

### ISSUE THREAD

**Issue by ghost** [redeclipse/world#188]
This map is suitable for deathmatch,defend and control,bomber ball and capture the flag.
[LostFortress.zip](https://github.com/redeclipse/world/files/5672697/LostFortress.zip)

**Comment by tiger-zhangc** [comment]
![Screenshot 2020-12-10 20-41-43](https://user-images.githubusercontent.com/75789534/101774006-7e61c780-3b28-11eb-8378-3002dcd72593.png)
![Screenshot 2020-12-10 20-42-36](https://user-images.githubusercontent.com/75789534/101774023-828de500-3b28-11eb-836d-f98a4f65c0c1.png)
![Screenshot 2020-12-10 20-42-44](https://user-images.githubusercontent.com/75789534/101774028-83267b80-3b28-11eb-8cd2-f63e596d7721.png)
![Screenshot 2020-12-10 20-43-42](https://user-images.githubusercontent.com/75789534/101774031-8457a880-3b28-11eb-815d-45adb29cade0.png)
![Screenshot 2020-12-10 20-43-49](https://user-images.githubusercontent.com/75789534/101774036-84f03f00-3b28-11eb-99d9-701d1131b7bc.png)
![Screenshot 2020-12-10 20-43-58](https://user-images.githubusercontent.com/75789534/101774041-86ba0280-3b28-11eb-82ce-d8f2fa7daa15.png)
![Screenshot 2020-12-10 20-44-04](https://user-images.githubusercontent.com/75789534/101774045-87529900-3b28-11eb-9f05-64abdb6a6bf8.png)

**Comment by tiger-zhangc** [comment]
This map can run on 2.0.0.

**Comment by qreeves** [comment]
Initial impressions are that this is your first map, things you will want to do is:

- Introduce more variation by using more textures and trims.
- Introduce more colour so that walls/ceilings/floors don't blend together.
- Use mapmodels to add more details.
- Reduce the "blocky" nature of the map by rounding edges and avoiding heavy use of square textures.
- Focus on having less open spaces and finding out if an area has a use when playing on it.
- Provide more cover in strategic locations (eg. paths from base to base).
- Improve flow by finding better locations for up/down paths rather than punching random holes in the floor/ceiling.
- Don't use ladders unless you absolutely need to, as they create "dead stops" and the player can already climb.
