### ISSUE TITLE
Regarding parkour/weapon changes

### ISSUE THREAD

**Issue by JeffBobbo** [redeclipse/world#32]
Please can we have the parkour and ammo changes that are being worked on cherry picked out of master into a feature branch before too much is done?

These changes are simply MASSIVE, a lot of things are broken or the new gameplay introduced is plain old bad for the game.

Removal of spiking means kicking is much harder, sword is nearly worthless. As a bug, I suspect, you can no longer double jump upwards and backwards.

The addition of weapon weights make balancing so much worse. shotgun, rifle, grenades, mines and rocket slows you down to a minuscule speed of 14, while sword and flamer let you zip around at 77 (yes, that's 550% the speed). This'll open up parkour lines for some players but not others, and more importantly, stops good use of parkour to head people off. Carrying light gear means streaking is more viable than it was. For some reason, being heavier means that using a pusher makes you faster (this isn't how physics works), to such an extent that actually being heavier means you can reach places you can't when you're lighter! An example of how ridiculous this is is on ghost. sg+rifle+mine+grenade+rocket, the pushers give you enough speed to push you PAST the building off the other side of the map, this is further than you could reach in 1.5 with a redirected pusher from the SAME side. With smg, you only just make it to the pusher on the other side.
~~Ammo doesn't contribute you weight like you might expect, having one grenade is the same as having two grenades, even though having one incurs a significant speed loss.~~
Overall the speed changes are pretty poor, a lot of players are harder to hit now because they're too fast, the hitzones are weird atm, and now I have to worry about ammo. The changes allow experienced players to exploit their knowledge even more against new players and the learning curve has become much more complicated.

The addition of ammo has some weird bugs. While on center there was three rockets, and eventually I managed to place one in a location and couldn't pick it up, SniperGoth couldn't even see it, but it was on my screen.
The ammo counts at the bottom should include what's currently in the weapon.
The weapon spawn mechanics make them farmable, to the extent that experienced players can deny the lesser skilled (and often newer) players from even getting weapons (this is very bad for game play). This could partially be fixed by only taking how much ammo you need to be full, and leaving the rest in the spawner like in other games. This does not completely fix the problem though, as ammo can be easily burnt by tossing weapons (in classic).

Multiplying health and damage by 10 was an unneeded change. While I'm glad for the extra precision, it does not need to be displayed to the user. The larger numbers are too much to take in quickly and the math is now so much more complicated.

It may be an engine issue, but something weird is going on with collisions. smg1 is super hard to use now and I was getting legshots while aiming at torso/head. I noticed that the attachment of the particle streams is incorrect, so this may be related
![image](https://user-images.githubusercontent.com/5425481/35476760-6788d0f4-03ad-11e8-837c-c74d60a3fdb0.png)

**Comment by SniperGoth** [comment]
I vote for this to be on it's own branch for experiments/fine tunning, if this will really be part of 2.0's release.
1.6's gameplay was very close to perfection (okay, okay, zapper2 was op and yadda yadda), the impulse count system was totally fine, so im not sure this will be the best course of action to evolve the game.
I just hope for the best.

**Comment by JeffBobbo** [comment]
I forgot to mention this earlier, but the new jumping behaviour is weird. It violates expectations of how gravity works (somehow, I'm heavier on the fall than I am on the rise) which makes estimating where you'll land from various heights. While the style of jumping may work well in side scrollers, it doesn't in FPS games.

Also, bots don't know what to do when they run out of ammo.

**Comment by qreeves** [comment]
Everyone seems to share the misconception that v2.0 is a continuation of the original game, when it is really a sequel. There's a reason it isn't going to be called v1.7; it is a departure from a lot of the things that were once set in stone. You should consider the master branch as an Alpha version for v2.0 rather than a complete game that's just receiving an iteration.

There's no point in a branch because it just limits the audience and ensures not enough testing is done on it before being merged. In the end, it is just as easy for me to either refine or remove things I have added, and after a certain point revert commits need to be manually fixed anyway, but they work.

I'm aware of some of the balancing issues already, as I had no real basis for the values that were chosen other than picking them out of the aether. Other things are just stuff I've picked for trials which may or may not change. The rest sounds like protocol issues or failing to update properly.

Right now, I am not really seeking feedback on any of this (yet) because I am still evaluating what direction I want to take this in. I especially don't want comparisons to the v1.x series, as it has run its course and I want the chance to (basically) start from scratch based on what I've learned and the systems I haven't been happy with.

**Comment by bonifarz** [comment]
Wow, so there will be a lot of new developments going on. I should take the time to have a look into this 😄

For now, I just wonder how you will consider to add these "weight" and inertia aspects to your so far awesome movement system.

> // physics.cpp: no physics books were hurt nor consulted in the construction of this code.
// All physics computations and constants were invented on the fly and simply tweaked until
// they "felt right", and have no basis in reality. Collision detection is simplistic but
// very robust (uses discrete steps at fixed fps).

The point I want to make here is that if you implement a mass modifier, it should mainly affect the way the actors are **accelerated**, and not their peak speed. Of course, you know about that, and I don't want to be the physicist that insists on a proper simulation, it is just meant as some guidance to get you back to that fine tuned state of what "feels right" 😉

Just keep going, I bet it will end up with something awesome again, but that may take some trial and error.

**Comment by qreeves** [comment]
Just to clarify, it's not that I'm not listening, just that this is going to be bumpy while I throw stuff at the wall and see what sticks. I am in no way discouraging further discussion, especially as the situation evolves.

**Comment by JeffBobbo** [comment]
>while I throw stuff at the wall

This is why I asked for separate branch (or even branches). It'd allow you to develop individual ideas and then chuck them out if you didn't want them.

The changes made last night were good, thank you. But my intention from the damage division thing was to provide integers for display (round health up, damage down), otherwise this just adds more to read (because now we have a decimal), although it occurred to me that increasing readability would help (remove glow/fade, reduce movement speed and give a clear outline).

I've also noticed I can't slide where I used to be able to, like after landing from a slide-launch thing, or from a double jump. I guess this is from an increase in the wait time between moves as spiking is slower now.

**Comment by SniperGoth** [comment]
Of the changes that were made, one that i miss is the "hold jump to go higher" mechanic that was implemented some days ago, and was reverted back to the older behavior.
It made the claw even way more useful, vertically speaking.
Going back to 1.6, i missed using it, actually, so i'd like for that to stay on the game.

**Comment by JeffBobbo** [comment]
Been playing around a bit this evening again with the new changes.

It seems impossible to multislide more than 2, SniperGoth says he can do 4 but mashing space I can't seem to get any more distance than I can with 2, after doing the second one I quickly revert to the crouch pose, meaning I can't launch either.

The lack of dashing is disappointing, it's not a move that allowed lots of movement on the ground, and tended to be annoying in the air, but it was really useful for sliding. Now it's impossible to start a slide from the crouch position, or to slide sideways/backwards.

It seems impossible to slide from a double jump, which is a massive momentum killer.

imo, impulsecount 5 is too small, and it should be restored to 6. We also need notification of how many moves we've got. Currently it's a blackbox that's unknown (and initially, I was like "wtf, why can't I climb/run/jump").

playerweight 150 is too low, in race it's like being a leaf and checkpoints serve no purpose now if you can keep going because there's no impulse (a bit like freestyle, what's going to happen to endurance?). weapon weights also seem too much.

damagedivisor stuff doesn't apply to obit health display.

**Comment by qreeves** [comment]
I've:
* added the ability to slide with any direction pressed
* fixed the ability to slide after a boost (bug)
* restored *impulsecount* to 6 and added an on-screen counter
* increased player weight in single-weapon modes
* fixed the *damagedivisor/damageinteger* for *showobithpleft*

The weapon mod settings are probably going to remain as placeholders until I can figure out the proper distribution of buffs and debuffs. Weapons that get higher damage buffs will likely see debuffs in the area of weight and/or speed (and/or health), with the inverse being true for other weapons (as seen with the *sword* at the moment).

**Comment by JeffBobbo** [comment]
Some more good changes.

I generally think the player weight should be higher, in all modes (and also be consistent), and then weapons don't add so much. Right now the difference between no, or light weapons, and heavy weapons is crazy. If your load out is sword and flamer or plasma, you have 170 weight, rocket adds 75 which is nearly half (and bare in mind, player weight is 150, so only 20 of that is weapons). Meanwhile shotgun+rifle is 260.
The capturecarryspeed works well, imo. It's not enough to be hugely noticeable, but is enough to make a difference, and this is how weapons should be more like.

Perhaps around 250 for playerweight, with the weight of weapons (don't know the varname to tweak) adding up to around 300 when fully loaded (i.e., the heaviest combination).

**Comment by SniperGoth** [comment]
Since we are at the topic of changes, what if we double tapped the crouch key while falling (since holding it while in the air makes us fall faster), we can impulse downwards and fall even faster?
Was thinking about this earlier this week, and maybe could be useful depending on the situation.
Any thoughts?

**Comment by lambda-11235** [comment]
@SniperGoth I'd totally accidentally do that over a precipice. It might work well though. I think Bobbo would love it, as it would allow melee players to get in close even quicker. I agree with @JeffBobbo on the weapon weights. The difference between unloaded and rifle/shotgun combe is really high.

**Comment by qreeves** [comment]
UPDATE: I've done a full review of all the weapon variables, which included putting the weights in the vicinity of where it was in 1.6 with smaller offsets.

**Comment by Dziq84** [comment]
please consider making zapper2 cooked without zoom ( zoom but where scope is?.. geez), with stronger projectile when full cooked, splash damage and big range.       this still can be good against rifles even, I remember that when I have zapper like that on my server, people liked it more than default ;p (no offence). Its still powerfull, no OP like now with proper vars and more original (now it just different rifle). Also still needs skill when using it, because you need to 'cook' it a second before shoot

**Comment by JeffBobbo** [comment]
fwiw, some players will play with the configuration that double tapping `c` will toggle their crouch mode.

I'll try to get around to playing with the new weights sometime soon and see what it's like.

**Comment by SniperGoth** [comment]
"Maybe we can finally use that old ground pound animation!"
Hmn... if we ever get to implement that, i'd rather it be used like the one from Halo 5.
You hold a key, then you aim where you want to be launched, BOOM.
As for RE, maybe the faster the player is when doing the move, the higher the area of effect/damage?
The biggest problem would be finding the best key combo, so it would be intuitive to use (or we could set it as a claw-only mechanic,hold mouse1/2 while looking down to use, who knows).

As for zapper 2 cooked, i remember in the earlier days when it was introduced on SVN, there was a cooked version of it, and it totally sucked, because of how inaccurate it was to properly use (you hold mouse2, it charges and shoots, you couldn't hold it charged, worked like plasma2 does), then it was returned to it's current 1.6 counterpart, so i vote for it to stay with the "phantom scope" for 2.0 .

**Comment by lambda-11235** [comment]
Still not sure about the weights, they seem a bit better though. Also, zapperrelasticity1 might be a bit to high. It's high rate of fire makes it difficult to aim with a high relasticity.

**Comment by qreeves** [comment]
You mean `zapperrelativity[1|2]`, right?

**Comment by V-ktor** [comment]
If the missing scope is the only problem of zapper2 the way to go is making a new model (rifle with scope).

**Comment by Dziq84** [comment]
I dont like it, its no more original weapon, strange pistol with phantom score, electricity without splash? again rifle users have another rifle to be happy with . . .

**Comment by lambda-11235** [comment]
I kind of agree with @Dziq84 in that I'm basically using the zapper as a rifle with stun capabilities and an option to shot close range. Of course, being a rifle user I love that :smile:. Another option is to have zapper2 have a short range but wider area of affect, like an EMP of something. That would be nice to get players off your back.

**Comment by JeffBobbo** [comment]
@Dziq84, @lambda-11235, the idea of moving zapper to a more long ranged weapon is to provide another option for long ranged combat than the rifle. REs weapons can be broken down into ranges of roughly <20m, <40m and above. For less than 20m there is sword, shotgun, and flamer (and claw/melee, plasma2), for less than 4 is where smg, plasma (1) and pistol make an appearance, this is also where zapper currently is. You can use these weapons over 40m, but their effectiveness wears off. After that all is left is rifle.

**Comment by lambda-11235** [comment]
@Dziq84 The problem is you have to aim and fire exactly when it's fully cooked, which can be difficult. For plasma you don't have to aim.

**Comment by Dziq84** [comment]
what are you talking about, zapper work exactly like a rifle, you cook - and shot when you need

**Comment by lambda-11235** [comment]
@Dziq84 About the version you posted, where it goes off when fully cooked.

**Comment by Dziq84** [comment]
And thats the problem? It needs skill, its a powerfull weapon , maybe hard to see that now, because vars are messed, but its just concept..  also there is splash damage and very big range
Problem with plasma it does not need skill and wht we got?    noobs with plasma winning matches...

**Comment by SniperGoth** [comment]
Something that has been bothering me is the current effectiveness of the sword, because the distance at which you can actually connect with enemies while using it is... a bit too small (see screenshot). 
![20180705102438](https://user-images.githubusercontent.com/24359960/42325877-e83bec38-803d-11e8-9344-ba3aa4193194.png)
This is the current distance the sword connects to the enemy player/bot, quite small and when everyone's moving, it's almost impossible to hit them/be hit.
My suggestion would be to increase the swordtrace value from 1.5 to 4, or a value between both, as it seems to work better for it.
![20180705102456](https://user-images.githubusercontent.com/24359960/42325995-3afeac30-803e-11e8-86e2-c8fe8b0acf3b.png) *swordtrace set to 4*

**Comment by IceflowRE** [comment]
4 distance looks a bit too far away.

**Comment by Dziq84** [comment]
I too think it's too far.

**Comment by nonoesimposible** [comment]
After testing out zapper for a while, I think the secondary fire should definitely have splash damage. Otherwise it's basically a weak smg as primary fire and a weak laser as secondary fire and (with a weight between the two).

**Comment by SniperGoth** [comment]
I don't agree with dziq's zapper vars, they make it look like the primary is a LMG of how hard it hits, and the secondary makes me remember of 1.3's super unbalanced rifle1, which did a massive splash damage.
I still vote for the current one to still be in place (with the phantom scope... but im trying to come up with something), as the zapper was never meant to be a strong weapon, and more of a utility/alternative to the rifle.

**Comment by qreeves** [comment]
In general, we don't really want *any* of the weapons copying another. The changes in the development version are just a stop gap measure. Originally, the intent was to create a Quake-like lightning gun, and I still want to see if I can pull that together somehow (requires a different way of doing the "projectiles").

**Comment by SniperGoth** [comment]
If the weapon, when firing, was instantaneous, instead of having a very small delay as it currently is (just keep firing a smg/zapper and keep strafing left and right to see what im talking about), and maybe make the projectile particle stay on the screen for a little longer, we could replicate it quite closely.
But i don't know if there's a var to control that kind of stuff, or if it is hardcoded, even if that would benefit a lot all the weapons, making them more precise, in the long run.
No idea if this would affect the general multiplayer lag though.
Or we could make it a hitscan weapon.
I still vote for the zoom ability to stay, it's quite useful to counter long distance rifle users with it :p

**Comment by IceflowRE** [comment]
Or just move the zapper to the blue ball weapon from Sauerbraten.

**Comment by Dziq84** [comment]
why zapper need to be counter-rifle ? Rifle is OP and now we have to worry about OP 'zappers' too?. Every weapon should be usefull to counter any other weapon, if there someone using rifle why I need to be forced to use zapper, because other weapons are way to crap compared to rifle?

**Comment by SniperGoth** [comment]
I'd say why don't we all here do a gathering and play the game, test stuff out, instead of discussing here, so we can have more of a real feel for the vars/weapons in general, to then do the feedback? 
And yes, i still stand for the zapper to counter the rifle supremacy.
The splash projectile that dziq's vars made could be used for another weapon ...  (me thinks of an acid-gun that throws stuff at the ground) imo. Just doesn't fit for me.

**Comment by drakovyrn** [comment]
Concerning Parkour, would it be unreasonable to change how parkour works in RE? I've always loved parkour and arena games, but I've never played a game that was good at both. The reason Red Eclipse doesn't cut it, is because the parkour side of things is rather hacky.

Check out this game, there's a free download for the Alpha v5 release where you can test the mechanics and maps: www.celaria.com

I've been playing this parkour game for a while, and the parkour is some of the most intuitive and fluid. I've asked the dev if he would add an instagib/deathmatch mode, but he only cares about parkour speedruns.

Pretty much, If I could make a game with the parkour of Celaria, and the arena deathmatch style shooting of Red Eclipse or Xonotic, I would, and it would be the perfect game for me.

And while yes, I _could_ technically start my own project doing just that, I'd much rather pitch it to some other potential projects, to save unnecessary work. This is the only other project interested in Parkour and Arena shooting, so I figured I'd ask. I also know this is a bit of a longshot, as changing the parkour system would heavily alter gameplay, and would require the redesign of many maps.

Just a thought. :)

**Comment by SniperGoth** [comment]
Ah you just have to get used to it, as parkour is a integral thing whitin RE's core gameplay itself.
For me it's almost perfect as it is, on RE2.0, even with the lack of dashing (#RIP). There's even a whole server dedicated exclusivelly to race (time trial) maps, and some i made myself.
Celaria seems interesting, i'll have a look at it later.

**Comment by qreeves** [comment]
Can't really tell what is different from the parkour just from the videos for this game, looks pretty much the same to me. What you feel about the mechanics is a subjective things, so perhaps you could elaborate on the specifics?

**Comment by drakovyrn** [comment]
The videos in question do not show much actual parkour, as they're usually just developer updates. The best videos that show off the basic mechanics of this game are user-made runthroughs. There are a lot of major differences between the two, not just from a subjective perspective, but from a functional one.

It's a shame that i don't know much about video editing, otherwise, I'd simply record myself playing both and explaining the multiple differences.

I'll write a post after this one explaining the differences in detail, but in the meantime, I would recommend watching [this video](https://www.youtube.com/watch?v=gaX2cBOnZtk&feature=youtu.be), as the showcased map is about testing one's proficiency in each of the game's basic mechanics (in loose order of the video):

jumping
vertical wall-run
landing impact roll
horizontal wall-run
redirected wall-jump
precise wall-jump
multiple wall-jumps
falling wall-jump
wall-jump through narrow space while tucked

One mechanic not really shown in the video is sliding, but I think that's a self-explanatory mechanic.

**Comment by qreeves** [comment]
We have most of these things, what they are mostly lacking is animations when compared to that video. The goals of the projects are fairly different, because we have a focus on skilled aiming and gun play, and therefore those things get prioritised over others.

While, on the surface, our mechanics seem basic due to the ease of accessibility, there is a whole other level one can attain by knowing the system and chaining the different moves together. What action you perform depends a lot on how you approach a surface, what angle you're facing, or the timing of a move after the previous one.

* Vertical wall-run: Performed by facing a wall and looking up or down while pressing the special key.
* Landing impact roll: Performed by holding crouch while landing on the ground. We don't roll the camera view because it'd be nausea inducing in a shooter game.
* Horizontal wall-run: Performed by facing parallel to a wall and pressing the special key.
* Redirected/precise/falling wall-jump: Performed by pressing jump while running along a wall, or by facing a wall directly with no up or down angle. All jumps are precise as you launch in the direction you are aiming and can be done at any time, even while falling.
* Multiple wall jumps: You can do this by default, but timing is important and you can only do so many without touching the ground. The number of in-air moves is 6 by default, and you can generally get in 3 wall jumps within the defined rules.
* Narrow space while tucked: You can do this by crouching, and you'll even slide when you hit the floor surface.

**Comment by drakovyrn** [comment]
The point of the video and the list was to draw attention to the differences in mechanics themselves, not to show RE is lacking features in general. Actually, what I feel RE is actually lacking is fluidity.

In Celaria, everything is controlled by jump and crouch -- in RE, you have jump, crouch, and parkour/kick.

So, going back through the list, I know how to use each of these moves in Celaria and RE, but it's how it's implemented in RE that feels hacky at times. I'm playing them side by side in order to capture some details. DO note that there are a few testing discrepancies. In Celaria, maps are very boxish/flat, and very open (sometimes large), while RE maps tend to be textured and small/tight-cornered, which makes it harder to really test features on an equitable level:

- Jumping (you omitted jumping in your list, but it's actually a key part of Celaria): In Celaria, the distance one jumps is dependent on how fast one is moving, as well as how long the jump button is held. I've noticed that in RE, a tap or a press on the jump button makes no difference, the player jumps the same height and distance on level ground, and only speed and the level of terrain is taken into account. If I wanted to jump across the top of a few pillars or small platforms, in Celaria, I'd have to aim, and jump with correct timing and precision. In RE, I would just have to jump and reposition myself mid-air to land on it. Celaria has very little air control, which means that successful moves requires careful planning and setup, because once you're in the air, there's not much else you can do. In RE, there's more room for error, and even if you're just slightly off in a parkour move in one of the racing maps, you can usually still fix it by spamming the jump and parkour keys.

- Vertical wall-run: In Celaria, one simply runs up to the wall, and press and holds jump. The height that the player goes up is dependent on how fast the player is moving, and how close the player is to the wall when they jump. Note that vertical view in Celaria is mostly for visual aide, looking up or down doesn't affect most (if any) of the moves or distance covered, but looking left or right does. In RE, one has to look straight up to do a proper vertical wall-run, otherwise, you have to spam jump and parkour to get up, and in RE, most of these moves are only affected by the amount of impulse power the player has. As long as the player has impulse power, the player can climb a wall for as long as the map height permits.

- Landing impact roll: In Celaria, landing from a high fall will jolt or stun the player, removing all the player's current momentum. To remedy this, the player holds crouch right before hitting the ground, and will roll into the fall. This ensures that the player maintains momentum, and isn't slowed down when in a timed-run. In RE, falling doesn't stun the player, so this isn't really a big deal and there isn't much reason to compare the two. However, crouch can still be held while falling to move into an impulse slide.

- Horizontal wall-run: In Celaria, the player must run up to a wall at an angle and press and hold the jump button to start wall-running. Speed determines how far one can wall-run, but the player is limited in height by an 'arch' and will only go up for a few seconds, before the wall-run starts going down. While wall-running in Celaria, the player can freely look around without affecting the wall-run. This enables the player to aim their next jump, especially if their next platform is 130° to their left or right. In RE, one runs up to a wall at an angle (or can even start from a standing position), and presses and holds the parkour key. To be honest, this is one of the more frustrating aspects of RE, and most different from Celaria. Wall-running in RE is always completely straight, and is continued for as long as you have impulse. While very different from Celaria, that in of itself is not bad. What I don't like, is that looking around detaches the player from the wall, and the player can only immediately detach from a wall by either jumping or waiting for the current impulse cycle to end. Ideally, the player should be able to detach from the wall as soon as the player stops holding the parkour button, and look range should be less limited so that a player can shoot an enemy around them while simultaneously wall-running.

- Redirected/precise/falling/multiple wall-jumps: In Celaria, Wall-jumping is simple. Run up to a wall, and while the player is in contact with the wall, the player can wall-jump off that wall in whatever direction they're looking by aiming and pressing the jump button. In RE,  there are two ways to do this. One, is to run facing directly at the wall and press the parkour button to kick of the wall, and then quickly turn around and try to redirect your jump while mid-air, or, go into a short wall-run and quickly aim and jumping in the direction you want to go in. I find that jumping back and forth between walls like Mario, or kicking off a wall to reach a ledge that's too high for a normal jump, is way easier and more intuitive to do in Celaria, than it is to do in RE. In RE, to jump between walls, one has to look straight up and use the parkour button, and then look down to kick off the wall and turn around quickly mid-air to face the wall to repeat the process. Otherwise, the character can run up the wall, and then aim in the direction they want to go, and then impulse jump in that direction. This isn't really wall-jumping, it's more just doing a vertical wall-run to double jump. This is actually what makes wall-jumping unintuitive, and while it works, and I know how to do it, it just seems like a lot of controls to go through before doing the actual action.

Basically, I just think that there are a few details that could be improved, and had I the knowledge, I'd even help out with them. I don't want to be that guy, but I'd say that the controls are more complicated than they need to be, and it could even use some QoL updates to it. And again, I'd like to reiterate that I've been playing since _2013_. I know the controls, I know how to play the game. I don't say this because I'm a noob and I need them to change so I can be better, it's simply because as I always say, just because it isn't broken, doesn't mean it can't be better. :P

Unfortunately, I don't really think this will go anywhere. A lot of the current playerbase probably likes things just as they are, and wouldn't be to happy about a major change to a system they're used to. Anyway, I just hope I've maybe given an idea or two to consider while development of 2.0 is going on, and maybe some of y'all will try out Celaria and have another awesome parkour game to play in your library. :]

**Comment by qreeves** [comment]
RE 2.0 is a reboot that is taking a serious look at the mechanics and refining them without (much) regard to the existing 1.x expectations, so never say never. I'll look back over this thread when I get back to work and pick some of the choice ideas to toy with, which is why I'm trying to get a better understanding of what you mean.

Some of the things mentioned here I actually played around with in the [Horizon](https://github.com/red-eclipse/horizon) experiment, but the idea there was to shift to melee combat and create a more natural feeling of movement. A lot of inspiration actually comes from Mirror's Edge and Prince of Persia, but in RE they were modified to suit the gameplay rather than being the core idea.

Of interest, I toyed around with the jump in 2.0 which you can read more about in topic #22 - in the end we decided to only change the speed of falling if crouch was being held. It may be that it just created an extra level of complication that is exacerbated by the current intricacies. It's hard to ever know why something feels wrong in isolation, when everything contributes to the end result. All I can do is guess and check... a million times.

**Comment by drakovyrn** [comment]
I've been thinking about some ideas for the last couple of days, and I've got a few ideas that I'd like to share when I get the chance. Some of these ideas might be easier from a visual point of view, however. Is there a good way to share drawn images so y'all can see?

**Comment by qreeves** [comment]
You can attach files to your posts here on GitHub, then use them inline.
