### ISSUE TITLE
Turn off friendly fire on defend-and-control and it's mutators by default?

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#43]
Some days ago i played a match of dac-king on dutility, something that is quite rare to be voted (1.6 btw).
But since the king point is on the middle (like any king of the hill map should be), both teams were going there, and teamkills were happening left and right.
Then, after some frustration, i decided to turn team damage off (teamdamagescale 0).
After this, the match became pretty fun to play in, as we didn't had anymore of those good and old random teamkills while holding the point.
So, while this has been said and such, what about making it have no teamdamage by default? Or even have shots not affect teammates (something like trialghost), maybe, because of the possible plasma2 spam that occurs in this type of situation?

**Comment by Sixardyh** [comment]
Maybe team damage should be toggled off only when the team mate is near the control point?

**Comment by JeffBobbo** [comment]
I think a coordinated team could abuse plasma2 in this type of scenario easily, locking it down.
Variations of this could also be done, like attaching mines to team mates and having them run in and then not die, yet still exploding the enemy.

Is plasma2 a massive cause of pain in king-dac? Or is just everything in general?

**Comment by robalni** [comment]
I think turning off team damage in one game mode but not in others feels wrong because the game rules should be consistent and predictable. What about adding a mutator that does it?

**Comment by SniperGoth** [comment]
I guess adding a mutator that does that could do it then.
It's just that i personally find it quite frustrating to play on DAC matches because of the constant teamkills.
And im sure im not the only that thinks that it doesn't get played often enough because of this particular problem.

**Comment by qreeves** [comment]
I agree that the rules should be consistent across the game, and this would probably be better serviced by a mutator.

The weapons that typically end up being the team-killers are designed the way they are as a sort of trade-off between power and danger, and turning off the team damage would likely overpower them. That being said, those weapons usually make use of the weapon variable to disable the penalties normally associated with team kills (points, etc).

**Comment by JeffBobbo** [comment]
Playing DAC the other day and thinking about this (although, it was instagib) I came to realise that probably a lot of the problem with DAC is there are too many points to control for the number of players, so the game ends up as a race around the map, rather than trying to actually defend points.

The buff also probably contributes to this; when a player is actively defending a point they tend to be pretty strong (from the buff) and in a 1on1 it's hard to overthrow (I usually try to rush in and get them out, and keep inside to overthrow to stop the buff). In all honesty though, if you want to retake a point, most of the time it's easier to go take a different one, causing them to leave to try to protect/retake it. This even works when there's only 2 or 3 points on the map, but is a mucher bigger problem on maps like ubik and deli where there's 7 or so points.

Regarding weapons; grenades and mines are mostly okay, people seem to learn to use them properly and do (despite the occasional accident). Plasma2 on the other hand is a weapon that not many experienced players use, some newer players use it (often to bad results) and other less-skilled players use it (sometimes to good use, but often not). Perhaps plasma2 just isn't a good fit for RE anymore and could be changed to something else?

**Comment by qreeves** [comment]
> probably a lot of the problem with DAC is there are too many points to control for the number of players
Yeah, I tend to agree, time to spruce up this mode or find a replacement?

**Comment by JeffBobbo** [comment]
> Yeah, I tend to agree, time to spruce up this mode or find a replacement?

From red-eclipse/base/issues/418, we could implement the KOTH changes and leave out the DAC ones (i.e., replace DAC with KOTH) until more players are around.
We could invert DAC's king mutator, i.e., by default there's only one base and you can choose "multi" as a mutator for multiple control points.
We could do a map pass to reduce the number of points.
