### ISSUE TITLE
HSL to prevent black players?

### ISSUE THREAD

**Issue by robalni** [redeclipse/world#67]
Black players are hard to see on dark maps and I don't like that some colors make it easier to survive than other colors.

One solution is to replace the RGB sliders with hue and saturation and maybe one for lightness with a range between 50% and 100%. What about that?

I think this would not only solve this problem but also make color selection more intuitive.

**Comment by Dziq84** [comment]
try /fullbrightmodels 100      ....or even bigger value, also you should mention about which game version you refer to

**Comment by robalni** [comment]
fullbrightmodels might help but there are still some problems:

- Not everybody knows about that variable.
- It's 0 by default so being black will still give you an advantage against many players.

I also think we should consider switching to HSL or HSV anyway just because it would give people a nicer color picking experience. Maybe we could have a circle with white or gray in the center and all the colors around it.

**Comment by lambda-11235** [comment]
Full bright models are in options under "gameplay/brighten models", so it's not extremely inaccessible. I would like to set it higher maybe, like to 50 or something, because on some maps I can be looking right at players and not see them. This gives an advantage, especially if it's default, as many people don't change or know what various options do.

**Comment by Dziq84** [comment]
keep in mind that RE 2.0 will not have these problems with dark players..  everything is fixed there
